apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spring-boot.fullname" . }}-conf
  labels:
    {{- include "spring-boot.labels" . | nindent 4 }}
data:
  app-config.json:
    '{
      "hibernate.connection.url": "jdbc:postgresql://{{ .Values.spring.db.url }}",
      "hibernate.connection.username": "{{ .Values.spring.db.user }}",
      "hibernate.connection.password": "{{ .Values.spring.db.password }}"
     }'