---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "letsencrypt-cluster-issuer-dns-aws.fullname" . }}
  labels:
    {{- include "letsencrypt-cluster-issuer-dns-aws.labels" . | nindent 4 }}
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: {{ .Values.email }}
    privateKeySecretRef:
      name: {{ include "letsencrypt-cluster-issuer-dns-aws.fullname" . }}
    solvers:
      - selector:
          dnsZones:
            - "{{ .Values.domain }}"
        dns01:
          route53:
            region: {{ .Values.aws.region }}
            hostedZoneID: {{ .Values.aws.zoneId }}
            role: {{ .Values.aws.roleArn }}