{{- if .Values.cluster -}}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "letsencrypt-issuers.fullname" . }}
  labels:
    {{- include "letsencrypt-issuers.labels" . | nindent 4 }}
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: {{ .Values.email }}
    privateKeySecretRef:
      name: {{ include "letsencrypt-issuers.fullname" . }}
    solvers:
      {{- toYaml .Values.solvers | nindent 6 }}
{{- end }}